### PR TITLE
writing docs

### PR DESCRIPTION
**Pull request by sixpearls**
@ixjlyons I'm starting to write docs! I put a bunch of it in the readme, which does not render well on github. Do you have suggestions for organizing? And obviously any editing, etc would be welcome.

I also added the `numpydoc` extension for the docstrings, which might be more trouble than it's worth. Their documentation has a [styleguide](https://numpydoc.readthedocs.io/en/latest/format.html), which suggested keeping the doc strings themselves easier to read un-rendered. I am not sure if the extension is worth the effort, but the style guide makes sense.

### CODE REVIEW

**Comment by ixjlyons** [comment]
Sorry for letting this sit forever.

> I also added the numpydoc extension for the docstrings, which might be more trouble than it's worth. Their documentation has a styleguide, which suggested keeping the doc strings themselves easier to read un-rendered. I am not sure if the extension is worth the effort, but the style guide makes sense.

Have you tried `sphinx.ext.napoleon`? It's built in to sphinx, which is kind of nice, but I'm not really sure if it has shortcomings compared to numpydoc. I get some warnings about toctree missing references with numpydoc but not napoleon, not sure why.

As far as organization goes, I reviewed a JOSS submission a little while ago that I thought had a pretty nice structure for their docs (https://kepler-mapper.scikit-tda.org/). It's a somewhat similar project in that it's an algorithm implementation with fairly technical background and narrow-ish scope. So something like:

- index page with some basic information, maybe a quick example just to show the basics of the API (i.e. show off scipy interpolate compatibility) -- can just be the README as I know you like to re-use that :)
- getting started/installation options (from PyPI, from git)
- background/theory (I also like that kepler-mapper had a list of applications, which doesn't necessarily need its own page and could go here)
- examples, benchmarks
- API

**Comment by sixpearls** [comment]
If it makes sense for the index page and the readme to be different, they don't have to be the same. But then I might be tempted to `include::` with `start-after` and `end-before` directives. Surely managing this would be better than having "wet" docs, right? (I don't know if I'm being facetious either!)

Thanks for the suggested outline. The Kepler mapper docs organization does seem good, so following it (with fewer sub-pages) makes sense to me. I'll let you know when I have a new draft.

I may ping you for updating installation instructions. Is it easy to make the package pip installable for users (the build is either part of CI or automated in setup.py)? The current work flow seems fine for developers.

**Comment by sixpearls** [comment]
The latest commits made the following changes:
1. Changed variables names in the `impl` modules so the `evaluate_spline` functiosn can have identical signatures
2. Changed a shape check in _bspl.pyx so spline can have mixed orders (discovered while writing example)
3. Re-writing readme including example.


The work raised these questions:
1. should we put examples in the doc strings? If so, should we/how do we use them as part of tests?
2. regardless of answer to previous (but especially if yes), might be nice to break up the API docs -- how do we put each function on its own page?
3. Cython in requirements-dev ? and/or cython requirement in a "feature"? These would primarily help with installing the cython version from source, but we can also just include instructions in the readme.
4. I had to add special directive to exclude impl class attribute. -- should we move it to a module attribute?

I would particularly appreciate @ixjlyons input on 3. and 4. above.

I also checked nomenclature difference between order and degree. Normally, we define order =max degree + 1 but we are using `order` for max degree. Unfortunately, it looks like `scipy.interpolate.BSpline` introduced this [nomenclature error](https://github.com/scipy/scipy/blob/2f34eaf5d62a8fa40a84c287d2ea4cbc5b3d7e3b/scipy/interpolate/_bsplines.py#L62-L63) although it is [inconsistent](https://github.com/scipy/scipy/blob/2f34eaf5d62a8fa40a84c287d2ea4cbc5b3d7e3b/scipy/interpolate/_bsplines.py#L80-L81). So I will update to use `degree` everywhere, consistently.

**Comment by ixjlyons** [comment]
> should we put examples in the doc strings? If so, should we/how do we use them as part of tests? 

I think short basic examples to show usage of different argument combinations are useful, similar to numpy/scipy docs. One thing that comes to mind is some users might not be familiar with what `__call__` is and how you use the object returned from the high-level functions. Plots would be nice I guess but not really necessary and I don't know off-hand how easy it is to set that up. They can be run as tests with expected interpreter output.

> regardless of answer to previous (but especially if yes), might be nice to break up the API docs -- how do we put each function on its own page?

Agreed. [autosummary](https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html) can do this but I remember not really liking the default behavior and didn't feel like messing around with templates. Since the API is pretty small, it might make sense to just manually create stub files with one `autofunction` directive each. Obviously prone to problems later on though.

> Cython in requirements-dev ? and/or cython requirement in a "feature"? These would primarily help with installing the cython version from source, but we can also just include instructions in the readme.

Currently cython is in both requirements files since the dev version includes everything in `requirements.txt`. Maybe it makes sense to remove it from `requirements.txt`, add it to `requiremements-dev.txt`, and add it to setup.py in `extras_require`.

> I had to add special directive to exclude impl class attribute. -- should we move it to a module attribute?

Yeah go ahead and move it. The practical difference between a class attribute and module attribute is pretty much nil as opposed to an instance attribute letting you set the bspl implementation per object.

**Pull request merged**
