### PR TITLE
Fixing codecov on azure, again

### PR DESCRIPTION
**Pull request by sixpearls**
Reverts kb-press/ndsplines#42

### CODE REVIEW

**Comment by sixpearls** [comment]
@ixjlyons I misread the code coverage report, it is showing 90% of the test code is covered if I run with the --cov (no argument value) flag. So I really am stuck with the discrepancy of azure and what I get on my machine.

**Comment by sixpearls** [comment]
@ixjlyons thanks for figuring out the command that would do the coverage report correctly. Could you look into why the cython implementation isn't usable in the tests?

**Comment by sixpearls** [comment]
I will work on fixing the calculus tests with the numpy implementation.

**Comment by ixjlyons** [comment]
My best guess at the moment is that the test step is looking in `./ndsplines` for the compiled `_bspl.*.so` file (i.e. an in-place build) but it's installed in the environment-wide Python path (`/opt/hostedtoolcache/Python/3.6.9/x64/lib.python3.6/site-packages`). All the output from the build/install step looks good to me so I don't know what else it could be.

Also it's a real problem that CI passes even though there are test failures. I think this is because each command in the `script` step (task?) is run regardless of whether or not the previous command failed. Since the last command succeeds, the whole step succeeds.

I will work on better understanding the azure pipelines config. I'm finding that there are so many different layers available (with some being shorthand for others etc.) that it's hard to tell what the best practices are to do different things.

**Comment by sixpearls** [comment]
Do you know why changing the command that runs tests would change the path? Previous azure configurations were able to import the cython implementation successfully.

**Comment by sixpearls** [comment]
Do you know why changing the command that runs tests would change the path? Previous azure configurations were able to import the cython implementation successfully.

**Comment by ixjlyons** [comment]
So, I can reproduce this locally. When you run `pytest`, ndsplines is imported from site-packages, but with `python -m pytest`, it's importing from the `ndsplines/` folder. From [pytest docs](http://doc.pytest.org/en/latest/pythonpath.html#invoking-pytest-versus-python-m-pytest):

> Running pytest with python -m pytest [...] instead of pytest [...] yields nearly equivalent behaviour, except that the former call will add the current directory to sys.path. See also Calling pytest through python -m pytest.

`pytest --cov ndsplines tests/` works for me locally. Let's give that another shot? An alternative would be to build in place.

Working on a commit to make the pipelines config easier to understand (and hopefully work). Should be done shortly.

**Comment by ixjlyons** [comment]
Welp back to 0% coverage. Need to step away for a bit but I'll figure this out today.

**Comment by sixpearls** [comment]
Thanks! Seems like using an in-place ndsplines install should work, at least on the one that runs the coverage report.

Also, I think the conditional stuff might be how we can make CI fail if the test fails.

**Comment by sixpearls** [comment]
You probably knew that, but it took me a while to figure out how to make only a single image run the test.

**Comment by ixjlyons** [comment]
:tada: Installing in editable mode seems to do the trick https://codecov.io/gh/kb-press/ndsplines/tree/efc2b9b3d48c10e047bea98b38a269a708e9cbb0/ndsplines

I think we can go ahead and merge this though I have some ideas for improving the testing setup.

**Pull request merged**
